### ISSUE TITLE
Not able to use it

### ISSUE THREAD

**Issue by ranjeetkr** [vvasiloud/AutoRelatedProducts-Magento2#2]
Hi,

I configured this extension in venush theme but how i can use it and where it will populate the data ?

Please help !!

Thanks

**Comment by vvasiloud** [comment]
Generally if you enable it shows products from the same category of the current product unless you assign related products manually.

Let me know if you still have problems and what version of Magento you are using. Normally is should be shows in the "Magento\Catalog\Block\Product\ProductList\Related" block of the product page. 

Check if you theme doesn't override it/has conflicts with some other extensions also.
