### ISSUE TITLE
Issue in related product price

### ISSUE THREAD

**Issue by mohsinleads** [vvasiloud/AutoRelatedProducts-Magento2#3]
We have install the extension in our site but there is issue all related product showing price of displayed product

you can check this link

https://www.grocerydeals.com.au/frozen-paper-cups-pack-of-8.html

![related issue](https://user-images.githubusercontent.com/31881429/39955562-a343d07e-55ee-11e8-94b2-5d05c2ed3c7a.png)

**Comment by vvasiloud** [comment]
if you take a look on the `Plugin\Magento\Catalog\Block\Product\ProductList\Related.php` the loaded collection is not manipulating the product or the price e.g `$category->getProductCollection()`.

Please check if it related to the template and there is a bug there. 
Also which version of Magento are you using?

**Comment by mohsinleads** [comment]
i am using 2.2.3 MG

**Comment by vvasiloud** [comment]
Please use `Store > Configuration > Advanced > Developer > Debug > Enabled Template Path Hints for Storefront > Yes` to check you template for related products
