### ISSUE TITLE
Out of stock product

### ISSUE THREAD

**Issue by terrybakshi** [vvasiloud/AutoRelatedProducts-Magento2#4]
Hi is there a way to exclude out of stock products to show in related products

**Comment by vvasiloud** [comment]
Hello, sorry for the late reply.

I added stockFIlter on dev branch 

https://github.com/vvasiloud/AutoRelatedProducts-Magento2/blob/2cbeaa2a5fc7fd7d02b5e8946bed8c7fcf95e61d/Vvasiloud/AutoRelatedProducts/Plugin/Magento/Catalog/Block/Product/ProductList/Related.php#L77

Let me know if it works for you

Cheers

**Comment by terrybakshi** [comment]
ok thanks will there be any settings to do or just it will be default inbuilt, or after installation it will work by itself?

**Comment by vvasiloud** [comment]
Hello, It will work by default.

**Comment by terrybakshi** [comment]
> Hello, It will work by default.
Hi can you also fix the issue where if the products page is refreshed the related products in category should change as well. As for now they just stay the same on every single page every time which is not good.

**Comment by vvasiloud** [comment]
> > Hello, It will work by default.
> > Hi can you also fix the issue where if the products page is refreshed the related products in category should change as well. As for now they just stay the same on every single page every time which is not good.

Hello, please see my answer for this on https://github.com/vvasiloud/AutoRelatedProducts-Magento2/issues/5

If your problem is fixed for out of stock products let me know to close this issue.
