### ISSUE TITLE
Related products not updating

### ISSUE THREAD

**Issue by terrybakshi** [vvasiloud/AutoRelatedProducts-Magento2#5]
It would be better if you can fix the issue where if the products page is refreshed the related products in category should change as well. As for now they just stay the same on every single page every time which is not good.

**Comment by secaliskan** [comment]
yes same issue, extension is not working. Once it sets the related 5 products and never changes...
Magento 2.3 php 7.2

**Comment by vvasiloud** [comment]
Hello, 

I added a change to show random products from this category instead.

 On dev branch:

https://github.com/vvasiloud/AutoRelatedProducts-Magento2/blob/7c12a6a966fba884eb1c65c51411371c0a4ab934/Vvasiloud/AutoRelatedProducts/Plugin/Magento/Catalog/Block/Product/ProductList/Related.php#L78

Let me know if this helps

**Comment by secaliskan** [comment]
Thank you I’ll update the extension then...


Sent from Yahoo Mail for iPhone


On Çarşamba, Ağustos 7, 2019, 12:04 ÖÖ, Vasilis Vasiloudis <notifications@github.com> wrote:


Hello,

I added a change to show random products from this category instead.

On dev branch:

https://github.com/vvasiloud/AutoRelatedProducts-Magento2/blob/7c12a6a966fba884eb1c65c51411371c0a4ab934/Vvasiloud/AutoRelatedProducts/Plugin/Magento/Catalog/Block/Product/ProductList/Related.php#L78

Let me know if this helps
