### ISSUE TITLE
Try to use as Upsell instead of Related products

### ISSUE THREAD

**Issue by alburni** [vvasiloud/AutoRelatedProducts-Magento2#6]
Hello, I tried to fork your module to override Upsell block instead of Related block.
But no upsell is displayed, do you think I missed something ? Thanks!

https://github.com/alburni/AutoRelatedProducts-Magento2/commit/59763b8003dd832d8e2298dd2d690125d58d0a7b

**Comment by vvasiloud** [comment]
Hi, you need to get upsell products from current product.

e.g when you get the current product:

`$product = $this->_registry->registry('current_product');//get current product`

Add the following and modify the rest of the behaviour as you like
`$upsellProducts = $product->getUpSellProducts();` 

Let me know if this helps

**Comment by alburni** [comment]
Currently, your extension makes links as "Related products". I wanted to change the link type to "Upsell products", as I tried on my fork. Maybe I missed something because it doesn't display upsells.
Thanks for you help!
